channels:
- conda-forge
dependencies:
- coverage
- google-api-python-client =2.198.0
- google-auth =2.55.1
- google-auth-oauthlib =1.4.0
- numpy =2.4.3
- pandas =3.0.2
- python
- scikit-learn =1.8.0
- sqlalchemy =2.0.51
- tqdm =4.68.4
- hatchling
- hatch-vcs
