channels:
- conda-forge
dependencies:
- coverage
- google-api-python-client =2.200.0
- google-auth =2.56.3
- google-auth-oauthlib =1.4.1
- numpy =2.5.1
- pandas =3.0.5
- python
- scikit-learn =1.9.0
- sqlalchemy =2.0.52
- tqdm =4.70.0
- hatchling
- hatch-vcs
- flask-login =0.6.3
