# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.12"
        channel-priority: strict
        environment-file: .ci_support/environment.yml
    - name: Test
      shell: bash -l {0}
      run: |
        pip install --no-deps .
        coverage run -a -m unittest discover tests
        coverage xml
    - name: Coveralls
      uses: coverallsapp/github-action@v2
